package model

import "github.com/zfoteff/quick-congress/pkg/quickcongress/model/dto"

type CongressesSuccessRes struct {
	Congresses      []dto.Congress      `json:"congresses"`
	Pagination      dto.Pagination      `json:"pagination"`
	RequestMetadata dto.RequestMetadata `json:"request"`
}

type CongressesErrorRes struct {
	CongressErrors CongressError `json:"error"`
}

type CongressError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type CongressesReqQuery struct {
	Format string
	Limit  uint16
	Offset uint16
}

type CongressesReqOptions struct {
	QueryString CongressesReqQuery
}

type AutoGenerated struct {
	Congresses []struct {
		EndYear  string `json:"endYear"`
		Name     string `json:"name"`
		Sessions []struct {
			Chamber   string `json:"chamber"`
			Number    int    `json:"number"`
			StartDate string `json:"startDate"`
			Type      string `json:"type"`
		} `json:"sessions"`
		StartYear string `json:"startYear"`
		URL       string `json:"url"`
	} `json:"congresses"`
	Pagination struct {
		Count int    `json:"count"`
		Next  string `json:"next"`
	} `json:"pagination"`
	Request struct {
		ContentType string `json:"contentType"`
		Format      string `json:"format"`
	} `json:"request"`
}
